version: '3.7'

networks:
  avia-network:

name: aviatracking

services:
  back-db:
    image: postgres:16-alpine
    container_name: 'back-db'
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
      POSTGRES_DB: "aviatracking"
    networks:
      avia-network:
    ports:
      - "4321:5432"
    secrets:
      - db_username
      - db_pass
  avia-back:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: deploy
    container_name: avia-back
    environment:
      DEBUG: true
      SPRINGDOC_PATH: /api-docs
      SPRINGDOC_UI_PATH: /swagger-ui/index.html
      DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      DATASOURCE_URL: jdbc:postgresql://back-db:5432/aviatracking
      APP_NAME: devops-back
      DATASOURCE_USERNAME: /run/secrets/db_username
      DATASOURCE_PASSWORD: /run/secrets/db_pass
    secrets:
      - db_username
      - db_pass
    networks:
      avia-network:
    ports:
      - "8080:8080"
    depends_on:
      - back-db
    command:
      - java
      - -jar
      - app.jar

secrets:
  db_username:
    environment: DATASOURCE_USERNAME
  db_pass:
    environment: DATASOURCE_PASSWORD


# https://github.com/moberwasserlechner/docker-secret-spring-post-processor